const mybookingsData = [
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Upcoming', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Completed', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Upcoming', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Completed', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Completed', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Upcoming', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Completed', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Upcoming', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Completed', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Completed', 
    },
    {   id:1,
        bookingdate:1,
        traveldate:2,
        start: 2,
        end: 3,
        status: 'Upcoming', 
    },
];

export default mybookingsData;